name: Generate Keystore Base64
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Make and Print Base64
        run: |
          keytool -genkey -v -keystore my-release-key.jks -alias myalias -keyalg RSA -keysize 2048 -validity 10000 -storepass 12345678 -keypass 12345678 -dname "CN=App, OU=Dev, O=App, L=City, S=State, C=IR"
          base64 my-release-key.jks > key_base64.txt
          cat key_base64.txt
